export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
export const SHOW_USER_DETAIL_DRAWER = "SHOW_USER_DETAIL_DRAWER";
export const HIDE_USER_DETAIL_DRAWER = "HIDE_USER_DETAIL_DRAWER";
