import React from "react";
import {
  CssBaseline,
  Drawer,
  AppBar,
  Toolbar,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Typography,
  Divider,
  Container,
  styled,
  Grid,
  Fab,
  Paper,
  ListSubheader,
  ListItemAvatar,
  Avatar,
  Box,
} from "@mui/material";
import IconButton from "@mui/icons-material/MoveToInbox";
import MenuIcon from "@mui/icons-material/Mail";
import AddIcon from "@mui/icons-material/Mail";
import SearchIcon from "@mui/icons-material/Mail";
import MoreIcon from "@mui/icons-material/Mail";
import SidebarComponent from "../components/helper/SidebarComponent";
import NavbarComponent from "../components/helper/NavbarComponent";
import ChatNavbarComponent from "../components/helper/ChatNavbarComponent";

const drawerWidth = 240;

const AppBarStyled = styled(AppBar)(({ theme }) => ({
  zIndex: theme.zIndex.drawer + 1,
}));

const DrawerContainer = styled("div")(({ theme }) => ({
  overflow: "auto",
  height: "100%",
}));

const messages = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
  },
];

const StyledFab = styled(Fab)({
  position: "absolute",
  zIndex: 1,
  top: -30,
  left: 0,
  right: 0,
  margin: "0 auto",
});

const DashboardLayout = ({ children }) => {
  return (
    <div>
      <CssBaseline />
      <Grid container spacing={0}>
        {/* Chat Sidebar (4 columns) */}
        <Grid item xs={12} sm={3} md={3} lg={3} xl={3}>
          <NavbarComponent />
          <Paper square sx={{ pb: "50px" }}>
            <List sx={{ mb: 2 }}>
              {messages.map(({ id, primary, secondary, person }) => (
                <React.Fragment key={id}>
                  <ListItem button>
                    <ListItemAvatar>
                      <Avatar alt="Profile Picture" src={person} />
                    </ListItemAvatar>
                    <ListItemText primary={primary} secondary={secondary} />
                  </ListItem>
                </React.Fragment>
              ))}
            </List>
          </Paper>
        </Grid>

        {/* Message Content Area (8 columns) */}
        <Grid item xs={12} sm={9} md={9} lg={9} xl={9}>
          <ChatNavbarComponent />
          {children}
        </Grid>
      </Grid>
    </div>
  );
};

export default DashboardLayout;
