module.exports = {
  NAME_IS_REQUIRED: "Name is required.",
  EMAIL_IS_REQUIRED: "Email is required",
  PASSWORD_IS_REQUIRED: "Password is required",
  VALID_EMAIL_IS_REQUIRED: "Valid Email is required",
  VALID_PHONE_IS_REQUIRED: "Valid Phone is required",
  USER_ALREADY_EXISTS: "User already exists",
  USER_NOT_FOUND: "User not found",
  INVALID_PASSWORD: "Invalid password",
  EMAIL_VERIFICATION_REQUIRED: "Email verification is required",
  USER_ID_IS_REQUIRED: "User id is required",
  EMIAL_CODE_IS_REQUIRED: "Email code is required",
  INVAILD_CODE: "Invalid code",
  EMAIL_IS_ALREADY_VERIFIED: "Email is already verified",
  FROM_ID_IS_REQUIRED: "From user id is required",
  TO_ID_IS_REQUIRED: "To user id is required",
  IS_GROUP_REQUIRED: "Is group required",
  ID_SHOULD_BE_CORRECT_MONGO_OBJECT_ID: "Id should be correct mongo object id",
  CREATED_BY_ID_IS_REQUIRED: "Created by id is required",
  GROUP_ALREADY_EXISTS: "Group alreay exists",
  GROUP_ID_IS_REQUIRED: "Group id is required",
  USER_DOES_NOT_EXIST_IN_GROUP: "User does not exists in the group",
  USER_REMOVED_FROM_GROUP: "User is removed from the group",
  MEMBERS_NOT_FOUND: 'Members not found in this Group',
  USER_LEFT_GROUP: "User has left the group",
  GROUP_DOES_NOT_EXISTS: "Group does not exists",
  USER_NOT_VERIFIED: 'User not verified',
  USER_ALREADY_EXISTS_IN_CONTACTS: 'User already exists in the contacts',
  INVAILD_USER_ID_FORMATE: 'Invalid user id format',
  PROFILE_ID_REQUIRED: 'ProfileId required',
  USER_IS_NOT_ADMIN: 'You are not Admin',
  USER_CANNOT_DELETE_SUPERADMIN: 'You cannot delete superadmin who created this group',
  SOME_THING_WENT_WRONG: 'Something went wrong',
  RECORD_NOT_FOUND: 'Record not found',
  IS_GROUP_ADMIN_REQUIRED: "Is group admin required",
  ADDING_USER_DOES_NOT_EXISTS: "Adding user does not exists",
  USER_ALREADY_EXISTS_IN_GROUP: "User already exists in the group",
  MEMBERS_ARE_REQUIRED: "Members are required",
  ATLEAST_ONE_MEMBER_SHOULD_BE_ADDED: "Atleast one member is required to create the group",
  IS_GROUP_REQUIRED: "Is group required",
  MESSAGE_DOES_NOT_EXISTS_FOR_USERS: "Message does not exists for these users",
  MESSAGE_ALREADY_DELETED: "Message is already deleted",
  IS_GROUP_IS_REQUIRED: 'is group required',
  MESSAGE_ID_REQUIRED: 'Message id is required',
  TO_CONTACT_ID_IS_REQUIRED: 'to contact id is required',
  MESSAGE_TYPE_IS_REQUIRED: 'Message type is required',
  YOU_CANNOT_MESSAGE_YOURSELF: 'You cannot message yourself',
  TYPE_SHOULD_BE_IN_THIS: 'Message Type should be in [ Text ,'
};
