module.exports = {
  NAME_IS_REQUIRED: "Name is required.",
  EMAIL_IS_REQUIRED: "EMail is required",
  PASSWORD_IS_REQUIRED: "Password is required",
  VALID_EMAIL_IS_REQUIRED: "Valid Email is required",
  VALID_PHONE_IS_REQUIRED: "Valid Phone is required",
  USER_ALREADY_EXISTS: "User already exists",
  USER_NOT_FOUND: "User not found",
  INVALID_PASSWORD: "Invalid password",
  EMAIL_VERIFICATION_REQUIRED: "Email verification is required",
  USER_ID_IS_REQUIRED: "userId is required",
  EMIAL_CODE_IS_REQUIRED: "Email code is required",
  INVAILD_CODE: "Invalid code",
  EMAIL_IS_ALREADY_VERIFIED: "Email is already verified",
  FROM_ID_IS_REQUIRED: "From user id is required",
  TO_ID_IS_REQUIRED: "To user id is required",
  IS_GROUP_REQUIRED: "Is group required",
  ID_SHOULD_BE_CORRECT_MONGO_OBJECT_ID: "Id should be correct mongo object id",
  CREATED_BY_ID_IS_REQUIRED: "Created by id is required",
  GROUP_ALREADY_EXISTS: "Group alreay exists",
  GROUP_ID_IS_REQUIRED: "Group id is required",
  USER_DOES_NOT_EXIST_IN_GROUP: "User does not exists in the group",
  USER_REMOVED_FROM_GROUP: "User is removed from the group",
  USER_LEFT_GROUP: "User has left the group",
  GROUP_DOES_NOT_EXISTS: "Group does not exists",
  IS_GROUP_ADMIN_REQUIRED: "Is group admin required",
  ADDING_USER_DOES_NOT_EXISTS: "Adding user does not exists",
  USER_ALREADY_EXISTS_IN_GROUP: "User already exists in the group",
};
